<section id="login">
    <div class="container h-100">
        <div class="row my-auto justify-content-center">
            <div class="col-lg-5 my-auto">
                <img src="https://i.imgur.com/aoBq0Om.png" alt="MVPGram" class="img-fluid">
            </div>
            <div class="col-lg-5 my-auto">
                <div class="box">
                    <div class="box-header">
                        <h2>MVPGram</h2>
                    </div>
                    <div class="box-content">
                        <form action="" method="post" class="formLogin">
                            <input type="text" class="form-control" placeholder="Nome de usuário, telefone ou e-mail" name="user">
                            <input type="password" class="form-control" placeholder="Senha" name="pass">

                            <input type="submit" class="btn btn-insta">
                        </form>
                    </div>
                </div>

                <div class="box">
                    <div class="box-content text-center">
                        Não tem uma conta? <a href="/accounts/register">Cadastre-se</a>
                    </div>
                </div>

                <div class="box box-hidden" id="msg">
                    <div class="box-content text-center">

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
