<section id="register">
    <div class="container">

        <div class="row justify-content-center">
            <div class="col-lg-5">
                <div class="box">
                    <div class="box-header">
                        <h2>MVPGram</h2>
                        <p>Cadastre-se para ver fotos e vídeos dos seus amigos.</p>
                    </div>
                    <div class="box-content">
                        <form action="" method="post" class="formRegister">
                            <input type="text" class="form-control" placeholder="Nome de celular ou e-mail" name="telefone">
                            <input type="text" class="form-control" placeholder="Nome completo" name="nome">
                            <input type="text" class="form-control" placeholder="Nome de usuário" name="usuario">
                            <input type="password" class="form-control" placeholder="Senha" name="pass">

                            <input type="submit" class="btn btn-insta">
                        </form>
                    </div>
                </div>

                <div class="box">
                    <div class="box-content text-center">
                        Tem uma conta? <a href="/accounts/login">Conecte-se</a>
                    </div>
                </div>

                <div class="box box-hidden" id="msg">
                    <div class="box-content text-center">

                    </div>
                </div>
            </div>
        </div>
    </div>

</section>