<section id="dashboard">
    <div class="container mt-3">
        <div class="row mx-auto">
            <div class="col-lg-7">
                <!-- Modelo publicação -->
                <?php
                    if (isset($posts)):
                        foreach ($posts as $post):
                ?> 
                    <div class="row">
                        <div class="col-lg-12">
                            <div class="card card-post">
                                <div class="card-header">
                                    <img class="post-usericon" src="<?=$post->imagemUsuario;?>" alt="João Artur">
                                    <span><?=$post->usuario;?></span>
                                </div>

                                <div class="card-body post-image" data-img="<?=$post->imagem;?>" data-idpost="<?=$post->id;?>">

                                </div>

                                <div class="card-footer">
                                    <div class="actionButtons">
                                        <div class="item likeButton" data-idPost="<?=$post->id?>">
                                            <i class="far fa-heart"></i>
                                        </div>
                                        <div class="item">
                                            <i class="far fa-comment"></i>
                                        </div>
                                        <div class="item">
                                            <i class="far fa-share-square"></i>
                                        </div>
                                    </div>

                                    <span class="text-bold">100 curtidas</span>

                                    <div class="post-comments">
                                        <div class="comment">
                                            <span class="user"><?=$post->usuario;?></span>
                                            <span class="text"><?=$post->descricao;?></span>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <?php
                        endforeach;
                    endif;
                ?>

            </div>
            <div class="col-lg-3">
                <h1>Stories</h1>
            </div>
        </div>
    </div>
</section>