<section id="dashboard">
    <div class="container mt-3">
        <div class="row mx-auto">
            <div class="col-lg-7">
                <!-- Modelo publicação -->
                <?php
if (isset($posts)):
    foreach ($posts as $post):
        $comments = json_decode($post->comments);
        ?>
				                        <div class="row" id="postContainer">
				                            <div class="col-lg-12 mb-2">
				                                <div class="card card-post">
				                                    <div class="card-header">
				                                        <img class="post-usericon" src="<?=$post->imagemUsuario;?>" alt="João Artur">
				                                        <span><?=$post->usuario;?></span>
				                                    </div>

				                                    <div class="card-body post-image" data-img="<?=$post->imagem;?>" data-idpost="<?=$post->id;?>">

				                                    </div>

				                                    <div class="card-footer">
				                                        <div class="actionButtons">
				                                            <div class="item likeButton" data-idPost="<?=$post->id?>">
				                                                <i class="<?=($post->liked > 0) ? 'text-danger fas' : 'far';?> fa-heart"></i>
				                                            </div>
				                                            <div class="item">
				                                                <i class="far fa-comment"></i>
				                                            </div>
				                                            <div class="item">
				                                                <i class="far fa-share-square"></i>
				                                            </div>
				                                        </div>

				                                        <span class="text-bold">100 curtidas</span>
				                                        <div class="post-comments" data-idpost="<?=$post->id;?>">
				                                            <?php if ($post->descricao != ''): ?>
				                                            <div class="comment">
				                                                <span class="user"><?=$post->usuario;?></span>
				                                                <span class="text"><?=nl2br($post->descricao);?></span>
				                                            </div>
				                                            <?php endif;
    foreach ($comments as $comment):
    ?>
		                                                    <div class="comment">
		                                                        <span class="user"><?=$comment->nome;?></span>
		                                                        <span class="text"><?=nl2br($comment->msg);?></span>
		                                                    </div>
		                                                    <?php
endforeach;
?>
                                        </div>
                                        <form method="POST" action="" class="d-flex commentContainer">
                                            <div class="w-100 d-inline p-2">
                                                <input type="hidden" name="id_post" value="<?=$post->id;?>">
                                                <input name="message" type="text" class="messageComment form-control" placeholder="Digite sua mensagem">
                                            </div>
                                            <div class="d-inline">
                                                <button class="submitComment h-100"><i class="fas fa-paper-plane"></i></button>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                <?php
endforeach;
endif;
?>

            </div>
            <div class="col-lg-3">
                <h1>Stories</h1>
            </div>
        </div>
    </div>
</section>