<section id="dash">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <form action="" method="post" enctype="multipart/form-data">
                    <input type="file" name="imagem" class="form-control">
                    <br>
                    <textarea name="descricao" placeholder="Descreva sua imagem..." class="form-control mb-2"></textarea>
                    <input type="submit" value="Enviar" class="btn btn-info pull-right">

                </form>
            </div>
        </div>
    </div>
</section>