<nav class="menu">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <a class="menu-logo" href="/">MVPGram</a>
            </div>
            <div class="col-lg-4">
                <form action="" method="post" class="formBusca">
                    <input type="text" class="form-control" placeholder="Busca">
                </form>
            </div>
            <div class="col-lg-4">
                <ul class="menu-ul">
                    <li><a href="/"><i class="fas fa-home"></i></a></li>
                    <li><a href="/direct"><i class="far fa-paper-plane"></i></a></li>
                    <li><a href="/explore"><i class="far fa-compass"></i></a></li>
                    <li><a class="menu-notifications" href="javascript:void(0)"><i class="far fa-heart"></i></a></li>
                    <li><a href=""><i class="far fa-user"></i></a></li>
                </ul>
            </div>
        </div>
    </div>

</nav>