<nav class="menu">
    <div class="container">
        <div class="row">
            <div class="col-lg-4">
                <a class="menu-logo" href="#">MVPGram</a>
            </div>
            <div class="col-lg-4">
                <form action="" method="post" class="formBusca">
                    <input type="text" class="form-control" placeholder="Busca">
                </form>
            </div>
            <div class="col-lg-4">
                <ul class="menu-ul">
                    <li><a href="/new-post"><i class="fa fa-plus-circle"></i></a></li>
                    <li><a href=""><i class="fa fa-compass"></i></a></li>
                    <li><a href=""><i class="fa fa-heart-o"></i></a></li>
                    <li><a href=""><i class="fa fa-user-o"></i></a></li>
                </ul>
            </div>
        </div>
    </div>

</nav>