<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title><?php echo \JetPHP\Model\Config::show('TITULO'); ?></title>

    <?php \JetPHP\Model\SEO::ready(); ?>

    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <link rel="stylesheet" href="/misc/css/bootstrap.css">
    <link rel="stylesheet" href="/misc/css/mvp.css">
</head>
<body>
